### ISSUE TITLE
Deploy your portfolio

### ISSUE THREAD

**Issue by bungaantonio** [Hamzabaloch08/protfolio#1]
Hi, you could implement your project on **Netlify** or **Vercel** so that people can see it before transferring it to their local machine

**Comment by Hamzabaloch08** [comment]
@bungaantonio 

> Hi, you could implement your project on **Netlify** or **Vercel** so that people can see it before transferring it to their local machine

@bungaantonio Bro i already deploy my project in vercel but its incomplete that's why i not add project link in discription/readme

**Comment by bungaantonio** [comment]
I hope you can finish it, bro

**Comment by Hamzabaloch08** [comment]
@bungaantonio It will complete soon
